# Generated by Django 5.2.10 on 2026-02-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='barber',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
