# Generated by Django 5.2.12 on 2026-04-15 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_duration_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='years_of_experience',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Barber experience can not be negative number!')]),
        ),
    ]
