# Generated by Django 5.2.10 on 2026-02-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slug_alter_barber_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(default='https://cdn.prod.website-files.com/6691f4c15ef1cd5c89763f60/68f3851f1a7ad765f1e118ba_Fade%20Hairstyle%20for%20Men.webp'),
            preserve_default=False,
        ),
    ]
