# Generated by Django 5.2.12 on 2026-04-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('have_full_access', 'Has full CRUD to all models')]},
        ),
    ]
