# Generated by Django 5.2.12 on 2026-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
