# Generated by Django 5.2.12 on 2026-03-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creation',
            new_name='created_at',
        ),
    ]
