# Generated by Django 5.2.12 on 2026-03-29 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, message='5 is the maximum rating.'), django.core.validators.MinValueValidator(0, 'You can not put negative rating!')]),
        ),
    ]
