# Generated by Django 5.2.12 on 2026-03-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='client',
            new_name='user_profile',
        ),
    ]
