# Generated by Django 5.2.10 on 2026-02-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0002_rename_name_barber_first_name_barber_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=20)),
                ('date_and_hour', models.DateTimeField()),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.barber')),
                ('services', models.ManyToManyField(related_name='bookings', to='services.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
