# Generated by Django 5.2.10 on 2026-02-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_delete_reservation'),
        ('services', '0003_service_slug_alter_barber_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.barber'),
        ),
    ]
