# Generated by Django 5.2.12 on 2026-03-19 14:03

import bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(max_length=20, validators=[bookings.validators.ClientPhoneValidator()]),
        ),
    ]
