# Generated by Django 5.2.12 on 2026-04-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_date_and_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_and_hour',
            field=models.DateTimeField(default=None),
        ),
    ]
